### ISSUE TITLE
Publish box position inside a topic

### ISSUE THREAD

**Issue by xEnVrE** [xEnVrE/cooperative_transport#1]
New feature required:
since the estimation of the position/attitude of the box is not required we need
a node that publishes the position/attitude of the box is required.
Also the size of the box is required.

**Comment by xEnVrE** [comment]
In order to close the issue you can have a look at this
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by GiulioRomualdi** [comment]
Features that will be implemented are:
- Arbitrary robots and box position in gazebo world
- Box's size and position are loaded in ROS parameters server.
